name: "Test and Deploy to Staging"

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    environment: staging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract non-public secrets
        env:
          FILES: ${{ secrets.FILES }}
        run: |
          echo "$FILES" | base64 --decode > compressed.zip && \
          unzip -qq compressed.zip && \
          rm compressed.zip

      - name: Copy docker compose configuration and environment secrets
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key_path: key.pem
          source: "docker-compose.yml,.env"
          target: "~/enghub"

      - name: Docker compose build and up
        uses: appleboy/ssh-action@v0.1.4
        env:
          ENVIRONMENT: staging
          SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key_path: key.pem
          envs: ENVIRONMENT,SHA
          script_stop: true
          script: |
            cd ~/enghub/enghub && git fetch --all && git checkout $SHA
            cd ~/enghub && docker-compose build && docker-compose up -d
            docker image prune -a --filter "until=24h"
